[package]
name = "sudoku-game"
version = "0.1.0"
# TODO: Change once codecup updates its configuration.
edition = "2015"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[profile.release]
opt-level = 2
